# defectvad/models/stfpm/model_config.yaml

#####################################################################
# Model
#####################################################################

model:
  name: stfpm
  module: defectvad.models.stfpm.torch_model
  class: STFPMModel

#####################################################################
# Trainer
#####################################################################

trainer:
  name: stfpm
  module: defectvad.models.stfpm.trainer
  class: STFPMTrainer

  params:
    backbone: resnet50
    layers: [layer1, layer2, layer3]

  max_epochs: 5
  validate: true

#####################################################################
# Base
#####################################################################

seed: 42

path:
  backbone: /home/namu/myspace/NAMU/backbones
  dataset: /home/namu/myspace/NAMU/datasets
  mvtec: /home/namu/myspace/NAMU/datasets/mvtec
  visa: /home/namu/myspace/NAMU/datasets/visa
  btad: /home/namu/myspace/NAMU/datasets/btad

#####################################################################
# Dataset
#####################################################################

dataset:
  name: mvtec
  module: defectvad.data.datasets
  class: MVTecDataset
  # path: /home/namu/myspace/NAMU/datasets/mvtec
  # category: bottle

  img_size: 256
  crop_size: null
  normalize: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

#####################################################################
# Dataloader
#####################################################################

dataloader:
  train:
    batch_size: 16

    params:
      shuffle: true
      drop_last: true
      num_workers: 8
      pin_memory: true

  test:
    batch_size: 8
    
    params:
      shuffle: false
      drop_last: false
      num_workers: 8
      pin_memory: true
  
